services:
  - type: web
    name: asupatri-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run_backend.py
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production